#IMAGE NAME WITH TAG TO BE RUN
IMAGE_NAME_WITH_TAG=$1
#PARAMETERS TO RUN THE IMAGE
#BUCKET NAME
B=$2
#PROJECT NAME
P=$3
#REGION OF MODEL DEPLOYMENT
R=$4
#URI OF PKL FILE
U=$5
#FRAMEWORK
F=$6
#VERSION BEGINING WORDS
V=$7
#MODEL NAME
M=$8

docker run -t ${IMAGE_NAME_WITH_TAG} ${B} ${P} ${R} ${U} ${F} ${V} ${M}  
